# 1단계: Node.js 이미지를 기반으로 빌드 스테이지를 설정합니다.
FROM node:20.11 as build-stage
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

# 2단계: Nginx 이미지를 기반으로 실행 스테이지를 설정합니다.
FROM nginx:stable-alpine as production-stage
COPY --from=build-stage /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]